#!/usr/bin/env node
/**
 * Create Pull Request for high confidence trust centers
 * Used by GitHub Actions workflow
 */
const { execSync } = require('child_process');

function createPullRequest(runType, count) {
  let title, body;
  
  if (runType === 'monthly_full') {
    title = `🔄 Monthly Full Refresh: ${count} high confidence trust centers`;
    body = `## 🔄 Monthly Full Refresh - Trust Center Discovery

This PR was automatically generated by the **monthly full refresh** workflow.

### 📊 Summary
- **Companies Added**: ${count}
- **Confidence Level**: 95%+ (Auto-PR threshold)
- **Verification Method**: CNAME lookup to known trust center hosts
- **Source**: YC Companies API (Full Refresh)
- **Run Type**: Monthly comprehensive scan

### 🔍 What was verified:
- ✅ CNAME points to known trust center hosting platform
- ✅ Domain follows trust center patterns (trust.domain, etc.)
- ✅ Content contains trust center keywords
- ✅ URL is accessible and returns 200 status
- ✅ **Catches companies that added trust centers since last month**

### 🏷️ Labels
- \`auto-discovered\`
- \`high-confidence\`
- \`trust-centers\`
- \`monthly-refresh\`

### 📋 Review Checklist
- [ ] Verify company names are correct
- [ ] Check trust center URLs are accessible
- [ ] Confirm platform detection is accurate
- [ ] Test that new entries appear in the main site

### 🚀 Ready to merge
These entries have been automatically verified and are ready for immediate merge.`;
  } else {
    title = `🤖 Weekly Discovery: ${count} high confidence trust centers`;
    body = `## 🎯 Weekly Trust Center Discovery

This PR was automatically generated by the weekly trust center discovery workflow.

### 📊 Summary
- **Companies Added**: ${count}
- **Confidence Level**: 95%+ (Auto-PR threshold)
- **Verification Method**: CNAME lookup to known trust center hosts
- **Source**: YC Companies API (New companies only)
- **Run Type**: Weekly incremental scan

### 🔍 What was verified:
- ✅ CNAME points to known trust center hosting platform
- ✅ Domain follows trust center patterns (trust.domain, etc.)
- ✅ Content contains trust center keywords
- ✅ URL is accessible and returns 200 status

### 🏷️ Labels
- \`auto-discovered\`
- \`high-confidence\`
- \`trust-centers\`

### 📋 Review Checklist
- [ ] Verify company names are correct
- [ ] Check trust center URLs are accessible
- [ ] Confirm platform detection is accurate
- [ ] Test that new entries appear in the main site

### 🚀 Ready to merge
These entries have been automatically verified and are ready for immediate merge.`;
  }
  
  // Use GitHub CLI to create PR
  const labels = ['auto-discovered', 'high-confidence', 'trust-centers'];
  if (runType === 'monthly_full') {
    labels.push('monthly-refresh');
  }
  
  const labelString = labels.map(label => `-l "${label}"`).join(' ');
  
  try {
    const prCommand = `gh pr create --title "${title}" --body "${body}" --base main ${labelString}`;
    console.log('Creating PR with command:', prCommand);
    execSync(prCommand, { stdio: 'inherit' });
    console.log('✅ Pull request created successfully');
  } catch (error) {
    console.error('❌ Failed to create pull request:', error.message);
    process.exit(1);
  }
}

// Get command line arguments
const runType = process.argv[2] || 'weekly_incremental';
const count = process.argv[3] || '0';

console.log(`Creating PR for ${runType} with ${count} companies`);
createPullRequest(runType, count);
